### ISSUE TITLE
Minor README improvement

### ISSUE THREAD

**Issue by MattiSG** [bredele/marc#4]
Hi there!

Congrats for marc, looks like a nice project  :)

Here’s a recommendation for the documentation: don't use a bold word as the placeholder element in the README. It makes it hard for the newcomer to understand if your substitution pattern is `__{{varname}}__` or just `{{varname}}` being in bold. At least, I can say I had to read it several times in order to be sure of the proper usage.

Best,
Matti

**Comment by bredele** [comment]
Hey Matti,

Thanks. I just changed the README, what do you think? Comment est le temps en France? 

Olivier

**Comment by MattiSG** [comment]
> I just changed the README, what do you think?

Better, much less ambiguous now  :)  See #3 also.

> Comment est le temps en France?

Il fait beau avec un [léger risque de cancer de poumon](http://www.rtl.fr/actualites/info/environnement/article/pollution-plus-de-30-departements-en-alerte-7770435018)…

Le départ au Canada valait-il le coup ?

**Comment by bredele** [comment]
froid très froid! #3 is done
